---
- name: Installing lamp on ubuntu 20.04
  hosts: all
  become: yes
  tasks:
    - name: apache installation
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: php libapache2-mod-php php-mysql installation
      ansible.builtin.apt:
        name: 
         - php
         - libapache2-mod-php
         - php-mysql
        state: present
    - name: copying files from src to des for info.php
      ansible.builtin.copy:
        src: ./info.php
        dest: /var/www/html/info.php
    - name: apache2 reload and start
      ansible.builtin.systemd:
        name: apache2.service
        enabled: true
        state: restarted
